---
## So normally I would set this to
## - hosts: all
## However I only want to run this on this foreman group
- hosts:  foreman_hostgroup_rhel7


  tasks:

  ## Create the Ansible users and groups













