---
## So normally I would set this to
## - hosts: all
## However I only want to run this on this foreman group
- hosts:  foreman_hostgroup_rhel7
  remote_user: root
  gather_facts: no

  tasks:

  ## Create the Ansible users and groups
    - name: Create the Ansible group
      group:
        name: ansible
        state: present
        gid: 1337

    - name: Create the Ansible user
      user:
        name: ansible
        comment: "Ansible service account"
        uid: 1337
        group: ansible
        generate_ssh_key: yes
        state: present

    - name: Set authorized key took from file
      authorized_key:
        user: ansible
        state: present
        ## Yes, it's an embedded key. It's not in use in any real systems anywhere.
        key: "{{ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCytCeOZtwKbmsz+VU1yTlUPPwunVpXPE/9CKpiUVB7aPnurh8AtZoY7DCAuTMI2MhFbqlFgAHB00jhJ///uZW7D4S/7KBmLJBltr61jrVkcakZti3nz+g3R2F4ux6DeNMiTAInpLp5YwXEeBhArkULvZLPcmakOS3LQpL47xsAoiwkXRjr+19enck+ooniLPtJLC4u7bjqZQ47j7+6P6dEIJRg3yZ4RcNVjrEMm7qNTsDqNbk7d6qsA1stHl+5v+B+mCz3hY6HVlALUuhPzKTahXdlUhmo40B0H5PkU0fnbvQjdTiQt7+VogLHinXIFau4tMjx/n3AS29LKtie5XSP }}"






