---
## So normally I would set this to
## - hosts: all
## However I only want to run this on this foreman group
- hosts:  foreman_hostgroup_rhel7
  remote_user: ansible
  gather_facts: no

  tasks:

  ## Install essential packages
  - name: add essential packages
    yum:
      name: "{{ item }}"
      state: latest

    with_items:
      - tree
      - vim
      - git
    become: yes
