---
## So normally I would set this to
## - hosts: all
## However I only want to run this on this foreman group
- hosts:  foreman_hostgroup_rhel7
  remote_user: ansible
  gather_facts: no
  become_user: root
  become_method: sudo

  tasks:
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes