---
## So normally I would set this to
## - hosts: all
## However I only want to run this on this foreman group
- hosts:  foreman_hostgroup_rhel7
  remote_user: ansible
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo


  tasks:

  ## Ping all the effected servers. This is usefule for checking
  ## the scope of the machines it will be run against.
    - name: Update the kernel packages
      yum:
        name: 'kernel*'
        state: latest


    - name: Checking if we need a reboot
      # NOTE: this string check is wrong so always comes back as "yes"
      shell: if [ $(rpm -q kernel | sort -Vr | head -n 1) != kernel-$(uname -r) ]; then echo "yes"; fi
      register: reboot
      ignore_errors: true

    - name: Reboot required
      command: shutdown -r now "Ansible kernel update applied"
      async: 1
      poll: 0
      ignore_errors: true
      when: reboot.changed


    - name: Task3 waiting for server to come back after 10.04 to 12.04
      local_action: wait_for host={{ ansible_ssh_host }} state=started


