---
## So normally I would set this to
## - hosts: all
## However I only want to run this on this foreman group
- hosts:  foreman_hostgroup_rhel7
  remote_user: ansible
  gather_facts: no

  tasks:

  ## Update security patches only
    - name: Update security patches only
      command: yum update-minimal --security -y
      become: yes

    - name: Force satellite to update its patch records
      command: katelo-package-upload
      become: yes

