---
## So normally I would set this to
## - hosts: all
## However I only want to run this on this foreman group
- hosts:  foreman_hostgroup_rhel7
  remote_user: ansible
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo


  tasks:

  ## Ping all the effected servers. This is usefule for checking
  ## the scope of the machines it will be run against.
    - name: Update the openscap client
      yum:
        name: 'rubygem-foreman_scap_client'
        state: latest


