---
  - name: Copy the empty password script to the host
    template:
      src: set_no_empty_passwords.sh.j2
      dest: /tmp/set_no_empty_passwords.sh
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the empty password script
    command: /tmp/set_no_empty_passwords.sh
    become: yes