---
  - name: Copy the password max age script to the host
    template:
      src: set_max_password_expirationj2
      dest: /tmp/set_max_password_expiration.sh
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the password max age script
    command: /tmp/set_max_password_expiration.sh
    become: yes