---
  - name: Set minimum number of digits
    template:
      src: set_min_password_digits.sh.j2
      dest: /tmp/set_min_password_digits.sh
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the password max age script
    command: /tmp/set_min_password_digits.sh
    become: yes
