---
  - name: Set minimum number of digits
    template:
      src: set_min_password_digits.sh.j2
      dest: /tmp/set_min_password_digits.sh
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the password max age script
    command: /tmp/set_min_password_digits.sh
    become: yes

  - name: Set minimum password length
    template:
      src: set_min_password_length.sh.j2
      dest: /tmp/set_min_password_length.sh
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Set minimum password length script
    command: /tmp/set_min_password_length.sh
    become: yes

  - name: Set minimum uppercase chars in passwords
    template:
      src: set_min_ucase_passwords.sh.j2
      dest: /tmp/set_min_ucase_passwords.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Set minimum uppercase chars in passwords script
    command: /tmp/set_min_ucase_passwords.sh.j2
    become: yes

  - name: Set minimum lowercase chars in passwords
    template:
      src: set_min_lcase_passwords.sh.j2
      dest: /tmp/set_min_lcase_passwords.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Set minimum lowercase chars in passwords script
    command: /tmp/set_min_lcase_passwords.sh.j2
    become: yes

  - name: Set deny repeated failed attempts
    template:
      src: set_deny_failed_password_attampts.sh.j2
      dest: /tmp/set_deny_failed_password_attampts.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Run repeat failed login deny script
    command: /tmp/set_deny_failed_password_attampts.sh.j2
    become: yes