---
  - name: Set AuditD policies
    template:
      src: set_auditd_policies.sh.j2
      dest: /tmp/set_auditd_policies.sh
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the set auditd policies script
    command: /tmp/set_auditd_policies.sh
    become: yes

  - name: Detect adjtimex tamper policies
    copy:
      src: set_auditd_tamper_adjtimex.sh.j2
      dest: /tmp/set_auditd_tamper_adjtimex.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the Detect adjtimex tamper policies script
    command: /tmp/set_auditd_tamper_adjtimex.sh.j2
    become: yes

  - name: Detect csettime tamper policies
    copy:
      src: set_auditd_tamper_csettime.sh.j2
      dest: /tmp/set_auditd_tamper_csettime.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes


  - name: Execute the Detect adjtimes tamper policies script
    command: /tmp/set_auditd_tamper_csettime.sh.j2
    become: yes

  - name: Detect localtime tamper policies
    copy:
      src: set_auditd_tamper_localtime.sh.j2
      dest: /tmp/set_auditd_tamper_localtime.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the Detect localtime tamper policies script
    command: /tmp/set_auditd_tamper_localtime.sh.j2
    become: yes

  - name: Detect stime tamper policies
    copy:
      src: set_auditd_tamper_stime.sh.j2
      dest: /tmp/set_auditd_tamper_stime.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the Detect localtime tamper policies script
    command: /tmp/set_auditd_tamper_stime.sh.j2
    become: yes

  - name: Detect setimeofday tamper policies
    copy:
      src: set_auditd_tamper_stod.sh.j2
      dest: /tmp/set_auditd_tamper_stod.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the Detect localtime tamper policies script
    command: /tmp/set_auditd_tamper_stod.sh.j2
    become: yes
