---
  - name: Set AuditD policies
    template:
      src: set_auditd_policies.sh.j2
      dest: /tmp/set_auditd_policies.sh
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the set auditd policies script
    command: /tmp/set_auditd_policies.sh
    become: yes

  - name: Detect adjtimex tamper policies
    copy:
      src: set_auditd_tamper_adjtimex.sh.j2
      dest: /tmp/set_auditd_tamper_adjtimex.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the Detect adjtimex tamper policies script
    command: /tmp/set_auditd_tamper_adjtimex.sh.j2
    become: yes

  - name: Detect csettime tamper policies
    copy:
      src: set_auditd_tamper_csettime.sh.j2
      dest: /tmp/set_auditd_tamper_csettime.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes


  - name: Execute the Detect adjtimes tamper policies script
    command: /tmp/set_auditd_tamper_csettime.sh.j2
    become: yes

  - name: Detect localtime tamper policies
    copy:
      src: set_auditd_tamper_localtime.sh.j2
      dest: /tmp/set_auditd_tamper_localtime.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the Detect localtime tamper policies script
    command: /tmp/set_auditd_tamper_localtime.sh.j2
    become: yes

  - name: Detect stime tamper policies
    copy:
      src: set_auditd_tamper_stime.sh.j2
      dest: /tmp/set_auditd_tamper_stime.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the Detect localtime tamper policies script
    command: /tmp/set_auditd_tamper_stime.sh.j2
    become: yes

  - name: Detect setimeofday tamper policies
    copy:
      src: set_auditd_tamper_stod.sh.j2
      dest: /tmp/set_auditd_tamper_stod.sh.j2
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the Detect localtime tamper policies script
    command: /tmp/set_auditd_tamper_stod.sh.j2
    become: yes

  - name: Configure file policies
    copy:
      src: "{{ item }}"
      dest: "/tmp/{{ item }}"
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    with_items:
      - audit_delete_events.sh
      - audit_ext_media.sh
      - audit_kernel_events.sh
      - audit_login_logout.sh
      - audit_mac.sh
      - audit_netmod.sh
      - audit_priv_cmd.sh
      - audit_session.sh
      - audit_sysadmin_events.sh
      - audit_usermod.sh
      - autidt_file_access.sh
      - lock_chmod.sh
      - lock_chown.sh
      - lock_fchmod.sh
      - lock_fchmodat.sh
      - lock_fchown.sh
      - lock_fchownat.sh
      - lock_fremovexttr.sh
      - lock_fsetxattr.sh
      - lock_lchown.sh
      - lock_lremovexttr.sh
      - lock_lsetxattr.sh
      - lock_removexttr.sh
      - lock_setxattr.sh
      - make_auditd_immutable.sh
      - set_extra_ntps_servers.sh
      - set_ssh_idle.sh
    become: yes

  - name: Execute the Detect localtime tamper policies script
    command: "/tmp/{{ item }}"
    with_items:
      - audit_delete_events.sh
      - audit_ext_media.sh
      - audit_kernel_events.sh
      - audit_login_logout.sh
      - audit_mac.sh
      - audit_netmod.sh
      - audit_priv_cmd.sh
      - audit_session.sh
      - audit_sysadmin_events.sh
      - audit_usermod.sh
      - autidt_file_access.sh
      - lock_chmod.sh
      - lock_chown.sh
      - lock_fchmod.sh
      - lock_fchmodat.sh
      - lock_fchown.sh
      - lock_fchownat.sh
      - lock_fremovexttr.sh
      - lock_fsetxattr.sh
      - lock_lchown.sh
      - lock_lremovexttr.sh
      - lock_lsetxattr.sh
      - lock_removexttr.sh
      - lock_setxattr.sh
      - make_auditd_immutable.sh
      - set_extra_ntps_servers.sh
      - set_ssh_idle.sh
    become: yes


