---
  - name: Copy the set expiration  script to the host
    template:
      src: set_max_password_expiration.j2
      dest: /tmp/set_max_password_expiration.sh
      owner: root
      group: wheel
      mode: "u=rwx,g=r,o=r"
    become: yes

  - name: Execute the set password expiration script
    command: /tmp/set_max_password_expiration.sh
    become: yes