---
  - name: "Create custom fact directory"
    file:
      path: "/etc/ansible/facts.d"
      state: "directory"
  - name: "Insert custom fact file"
    copy:
      src: files/*.fact
      dest: /etc/ansible/facts.d/
      mode: 0755

  - name: "Re-run setup to use custom facts"
    setup: ~