---
  ## Install essential packages
  - name: add essential packages
    yum:
      name: "{{ item }}"
      state: latest

  ## This list is the name of the RPM's we are looking to install.
    with_items:
      - tree
      - vim
      - git
      - openscap
      - openscap-scanner
      - openscap-utils
    become: yes