---
  - name: "Generate and deploy the MOTD"
    include: motd.yaml

  - name: "Install the base packages all machines require."
    include: install_essential_packages.yaml

  - name: "Install and update the OpenSCAP client."
    include: update_openscp_clients.yaml

